export const Data = [
  {
    image: 'https://example.com/image1.jpg',
    icon: 'https://example.com/icon1.png',
    title: 'Item 1',
    date: '2023-10-21',
    subtitle: 'Description for Item 1',
    button: 'Click Me',
    trophy: 'Gold Trophy',
  },
  {
    image: 'https://example.com/image2.jpg',
    icon: 'https://example.com/icon2.png',
    title: 'Item 2',
    date: '2023-10-22',
    subtitle: 'Description for Item 2',
    button: 'Press This',
    trophy: 'Silver Trophy',
  },
  {
    image: 'https://example.com/image3.jpg',
    icon: 'https://example.com/icon3.png',
    title: 'Item 3',
    date: '2023-10-23',
    subtitle: 'Description for Item 3',
    button: 'Tap Now',
    trophy: 'Bronze Trophy',
  },
  {
    image: 'https://example.com/image4.jpg',
    icon: 'https://example.com/icon4.png',
    title: 'Item 4',
    date: '2023-10-24',
    subtitle: 'Description for Item 4',
    button: 'Explore',
    trophy: 'Platinum Trophy',
  },
  {
    image: 'https://example.com/image5.jpg',
    icon: 'https://example.com/icon5.png',
    title: 'Item 5',
    date: '2023-10-25',
    subtitle: 'Description for Item 5',
    button: 'Learn More',
    trophy: 'Diamond Trophy',
  },
  {
    image: 'https://example.com/image6.jpg',
    icon: 'https://example.com/icon6.png',
    title: 'Item 6',
    date: '2023-10-26',
    subtitle: 'Description for Item 6',
    button: 'Download Now',
    trophy: 'Ruby Trophy',
  },
  {
    image: 'https://example.com/image7.jpg',
    icon: 'https://example.com/icon7.png',
    title: 'Item 7',
    date: '2023-10-27',
    subtitle: 'Description for Item 7',
    button: 'Get Started',
    trophy: 'Emerald Trophy',
  },
  {
    image: 'https://example.com/image8.jpg',
    icon: 'https://example.com/icon8.png',
    title: 'Item 8',
    date: '2023-10-28',
    subtitle: 'Description for Item 8',
    button: 'Sign Up',
    trophy: 'Sapphire Trophy',
  },
];
